version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    volumes:
      - ./src:/app/src  # Mount the source code directory for live changes
      - ./public:/app/public  # Mount the public directory
    environment:
      - NODE_ENV=development  # Set the environment to development
