version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.15.0-browsers
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package-lock.json" }}
      - run:
          name: Build app
          command: npm run build
      - run:
          name: Test app
          command: npm run test
      - store_artifacts:
          path: ~/app/build
          destination: builds
      - store_test_results:
          path: ~/app/test-results

  deploy:
    docker:
      - image: circleci/node:14.15.0-browsers
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build app
          command: npm run build

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
