version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15.0-browsers
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Build app
          command: yarn build
      - run:
          name: Test app
          command: yarn test
      - store_artifacts:
          path: ~/app/build
          destination: builds
      - store_test_results:
          path: ~/app/test-results
  deploy:
    docker:
      - image: circleci/node:14.15.0-browsers
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build app
          command: yarn build
      - deploy:
          name: Deploy app
          command: |
            aws s3 sync build s3://example-bucket
            aws cloudfront create-invalidation --distribution-id DISTRIBUTION_ID --paths "/*"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
             
